# Generated by Django 4.0.3 on 2023-03-05 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expire_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='만료일'),
            preserve_default=False,
        ),
    ]
